### ISSUE TITLE
`afcp` vs Base `R`

### ISSUE THREAD

**Issue by vincentarelbundock** [astrezhnev/afcp#1]
Thanks for sharing this package.

I’m confused by how AFCP are computed. I’m working off the simplest plain word definition here:

And my example is from the `afcp` vignette, with a single Language Skills attribute:

``` r
library(cjoint)
library(afcp)
data("immigrationconjoint")
dat <- immigrationconjoint

# Automatic
f <- Chosen_Immigrant ~ `Language Skills`
amce_results <- amce(f, data=dat, cluster=T, respondent.id = "CaseID", design = "uniform")
afcp_results <- afcp(amce_results, respondent.id = "CaseID", task.id = "contest_no", profile.id = "profile", attribute = "Language Skills")
afcp_results$afcp

                      level      baseline      afcp         se     zstat
    1         brokenEnglish fluentEnglish 0.4067416 0.01658803 -5.622030
    2 triedEnglishbutunable fluentEnglish 0.3763066 0.01685034 -7.340705
    3       usedinterpreter fluentEnglish 0.3610799 0.01592112 -8.725525
              pval conf_high  conf_low conf_level
    1 1.887265e-08 0.4392535 0.3742296       0.95
    2 2.124724e-13 0.4093327 0.3432806       0.95
    3 2.649493e-18 0.3922847 0.3298750       0.95
```

Based on the definition above, I expected to be able to compute the AFCP for “Interpreter vs. Fluent” as follows:

``` r
# Filter out comparisons involving other language skills levels 
dat_acfp <- split(dat, list(dat$CaseID, dat$contest_no))
dat_acfp <- Filter(function(x) {
  all(c("used interpreter", "fluent English") %in% x[["Language Skills"]])
  }, dat_acfp)
dat_acfp <- do.call("rbind", dat_acfp)

# E[Chosen|Skill] in each Language Skill level of interest
cp <- aggregate(Chosen_Immigrant ~ `Language Skills`, FUN = mean, data = dat_acfp)

# E[Chosen|Fluent] - E[Chosen|Interpreter]
diff(cp$Chosen_Immigrant)

    [1] -0.2778403
```

But the result is different. In fact, the quantity labelled as `afcp` from your package appears to just correpond to the probability that a “Intepreter” immigrant is chosen in the relevant subset of comparisons, and *not* to the difference in probability.

``` r
cp

       Language Skills Chosen_Immigrant
    1   fluent English        0.6389201
    2 used interpreter        0.3610799
```

What am I missing?

**Comment by astrezhnev** [comment]
The AFCP between level a and b is defined as the probability that, among tasks where level a appears in one profile and level b appears in the other profile, a is selected. So it should be between 0 and 1.

It appears that you are getting it correctly from the aggregate function - You have `AFCP(fluent English, used interpreter)` and `AFCP(used interpreter, fluent English)`. These sum to 1 by construction.

**Comment by vincentarelbundock** [comment]
Thanks a lot for the clarification!

Turns out that the AFCP in your vignette is trivial to compute using the `marginaleffects` package. I think this approach is pretty cool because:

- Analysts can easily swap-in a Bayesian, ML, or whatever model they like to estimate the conditional expectations.
- It makes the connection between estimates and statistical model clear.
- Regressors don’t need to be categorical.
- Access to all the `marginaleffects` benefits like alternative vcov, bootstrap, etc.

Obviously, this doesn’t really have anything to do with the `afcp` package, but I’ll still post an example below in case you are curious.

#### Load libraries, data, select columns, and clean labels

``` r
library(cjoint)
library(afcp)
library(data.table)
library(marginaleffects)
data("immigrationconjoint")

dat = data.table(immigrationconjoint)[, .(
  choice = Chosen_Immigrant,
  job = Job,
  language = `Language Skills`,
  respondent = CaseID,
  task = contest_no,
  profile)]

levels(dat$language) = gsub(" +", " ", trimws(gsub("English", "", levels(dat$language))))

head(dat)
```

       choice                 job         language respondent  task profile
        <num>              <fctr>           <fctr>      <int> <int>   <num>
    1:      1               nurse tried but unable          4     1       1
    2:      0 child care provider used interpreter          4     1       2
    3:      0            gardener           fluent          4     2       1
    4:      1 construction worker           fluent          4     2       2
    5:      1               nurse           broken          4     3       1
    6:      0 child care provider           fluent          4     3       2

#### Wide data

Add “wide” data to the original data frame. For each respondent-task, we create new columns called `language_1` and `language_2`, where the digit identifies the profile. Note that we still preserve the original "long" structure. The "wide" data are just added as extra meta-info.

``` r
wide = dcast(dat, 
  respondent + task ~ profile,
  value.var = c("language", "job")
)
dat = merge(dat, wide)
head(dat)
```

    Key: <respondent, task>
       respondent  task choice                 job         language profile       language_1       language_2    job_1               job_2
            <int> <int>  <num>              <fctr>           <fctr>   <num>           <fctr>           <fctr>   <fctr>              <fctr>
    1:          4     1      1               nurse tried but unable       1 tried but unable used interpreter    nurse child care provider
    2:          4     1      0 child care provider used interpreter       2 tried but unable used interpreter    nurse child care provider
    3:          4     2      0            gardener           fluent       1           fluent           fluent gardener construction worker
    4:          4     2      1 construction worker           fluent       2           fluent           fluent gardener construction worker
    5:          4     3      1               nurse           broken       1           broken           fluent    nurse child care provider
    6:          4     3      0 child care provider           fluent       2           broken           fluent    nurse child care provider

#### Contrast labels

Create a new column to record what comparison each row represents. This is the variable with respect to which we marginalize to get the AFCP:

``` r
dat[, contrast := fifelse(
  language == language_1,
  paste(language, "vs.", language_2),
  paste(language, "vs.", language_1))
]
```

#### Estimate using `cjoint` and `afcp` packages

``` r
amce_results <- amce(
  choice ~ language,
  data=dat,
  cluster=T,
  respondent.id = "respondent",
  design = "uniform")

afcp_results <- afcp(
  amce_results,
  respondent.id = "respondent",
  task.id = "task",
  profile.id = "profile",
  attribute = "language")

afcp_results$afcp
```

                level baseline      afcp         se     zstat         pval conf_high  conf_low conf_level
    1          broken   fluent 0.4067416 0.01658803 -5.622030 1.887265e-08 0.4392535 0.3742296       0.95
    2  triedbutunable   fluent 0.3763066 0.01685034 -7.340705 2.124724e-13 0.4093327 0.3432806       0.95
    3 usedinterpreter   fluent 0.3610799 0.01592112 -8.725525 2.649493e-18 0.3922847 0.3298750       0.95

#### Estimate using `marginaleffects`


``` r
mod = lm(choice ~ factor(profile) * (language_1 * language_2), dat)

avg_predictions(mod, by = "contrast", vcov = ~respondent)
```


                                  Contrast  Estimate   Std. Error            z Pr(>|z|)      S     2.5 %    97.5 %
     broken vs. broken                     0.5000000 3.828245e-09 1.306081e+08  < 0.001    Inf 0.5000000 0.5000000
     broken vs. fluent                     0.4067416 1.661939e-02 2.447391e+01  < 0.001  437.0 0.3741682 0.4393150
     broken vs. tried but unable           0.5765363 1.682844e-02 3.425965e+01  < 0.001  852.1 0.5435532 0.6095194
     broken vs. used interpreter           0.6191562 1.653567e-02 3.744368e+01  < 0.001 1016.9 0.5867469 0.6515655
     fluent vs. broken                     0.5932584 1.661939e-02 3.569675e+01  < 0.001  924.7 0.5606850 0.6258318
     fluent vs. fluent                     0.5000000 1.184570e-09 4.220939e+08  < 0.001    Inf 0.5000000 0.5000000
     fluent vs. tried but unable           0.6236934 1.685684e-02 3.699941e+01  < 0.001  993.0 0.5906546 0.6567322
     fluent vs. used interpreter           0.6389201 1.591384e-02 4.014871e+01  < 0.001    Inf 0.6077296 0.6701107
     tried but unable vs. broken           0.4234637 1.682844e-02 2.516357e+01  < 0.001  461.7 0.3904805 0.4564468
     tried but unable vs. fluent           0.3763066 1.685684e-02 2.232367e+01  < 0.001  364.3 0.3432678 0.4093454
     tried but unable vs. tried but unable 0.5000000 7.629839e-09 6.553218e+07  < 0.001    Inf 0.5000000 0.5000000
     tried but unable vs. used interpreter 0.5411914 1.847661e-02 2.929062e+01  < 0.001  624.1 0.5049779 0.5774049
     used interpreter vs. broken           0.3808438 1.653567e-02 2.303165e+01  < 0.001  387.5 0.3484345 0.4132531
     used interpreter vs. fluent           0.3610799 1.591384e-02 2.268968e+01  < 0.001  376.2 0.3298893 0.3922704
     used interpreter vs. tried but unable 0.4588086 1.847660e-02 2.483187e+01  < 0.001  449.8 0.4225951 0.4950221
     used interpreter vs. used interpreter 0.5000000 1.013477e-08 4.933509e+07  < 0.001    Inf 0.5000000 0.5000000

    Columns: contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high 
    Type:  response

**Comment by astrezhnev** [comment]
Right, the AFCP is just an alternative estimand for conjoint experiments, but estimation is as simple as for the AMCE. It's straightforwardly identified by a simple sample mean, but one can improve precision with covariate adjustment, just as you would for any regression estimator.

One small note though is that in the case of fully factorial experiments, treatments are by definition categorical (high-dimensional, but still discrete). It's not clear to me what you mean by "regressors don't need to be categorical" - the particular treatments of interest are given by the experimental design not by model choice. There's not really a definition of this quantity for continuous treatments and it's not clear to me what that would be - at least without making additional modeling assumptions that are not guaranteed by the design.  

But otherwise, yes - it's just a sample mean in the same way that the standard AMCE estimator is a simple difference-in-means.

**Comment by vincentarelbundock** [comment]
It's a nice elegant idea. good work!
